
const IMAGE_BOUNDS=[[51.20,-10.92],[55.62,-5.18]];
const map=L.map("map",{zoomControl:true,minZoom:6,maxZoom:12,maxBounds:[[50.85,-11.25],[56.05,-4.80]],maxBoundsViscosity:.85,attributionControl:false,zoomSnap:.25});
L.imageOverlay("noiseisland.png",IMAGE_BOUNDS,{opacity:1,interactive:false,zIndex:1}).addTo(map);
map.fitBounds(IMAGE_BOUNDS,{padding:[18,18]});
const $=id=>document.getElementById(id),panel=$("infoPanel"),title=$("panelTitle"),kicker=$("panelKicker"),description=$("panelDescription"),artistList=$("artistList");
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function tagText(v){return String(v||"").trim().replace(/^#+/,"").replace(/\s+/g,"").replace(/[^A-Za-z0-9À-ÿ_-]/g,"")}
function tags(a){let t=[];if(a.genre)a.genre.split(/[,;|/]+/).map(x=>x.trim()).filter(Boolean).forEach(x=>t.push("#"+tagText(x)));(a.locationTags||[]).filter(Boolean).forEach(x=>t.push("#"+tagText(x)));return [...new Set(t)].filter(x=>x!="#")}
function card(a){const t=tags(a);return `<article class="artist-card"><div class="artist-name">${esc(a.artist)}</div>${t.length?`<div class="hashtags">${t.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div>`:""}${a.notes?`<div class="artist-note">${esc(a.notes)}</div>`:""}${a.link?`<a class="artist-link" href="${esc(a.link)}" target="_blank" rel="noopener noreferrer">Visit artist link ↗</a>`:`<div class="no-link">No link provided in the spreadsheet.</div>`}</article>`}
function openPanel(){panel.classList.add("open")}$("closePanel").onclick=()=>panel.classList.remove("open");$("resetMap").onclick=()=>map.fitBounds(IMAGE_BOUNDS,{padding:[18,18]});
fetch("data.json").then(r=>r.json()).then(data=>{
const byCity=new Map();data.artists.forEach(a=>(a.locations||[]).forEach(c=>{if(!byCity.has(c))byCity.set(c,[]);byCity.get(c).push(a)}));
function openArtist(a,fly=true){kicker.textContent="ARTIST";title.textContent=a.artist;description.textContent=a.locationRaw?`Location: ${a.locationRaw}`:"No Ireland location recorded.";artistList.innerHTML=card(a);openPanel();if(fly&&a.locations?.[0]){const c=data.cities.find(x=>x.name===a.locations[0]);if(c)map.flyTo([c.lat,c.lng],8.4,{duration:.6})}}
function openCity(c,list){kicker.textContent="ARTISTS IN";title.textContent=c.name;description.textContent=`${list.length} artist${list.length===1?"":"s"} connected to this place.`;artistList.innerHTML=list.map(card).join("")||"<div class='artist-card'>No artists mapped here.</div>";openPanel();map.flyTo([c.lat,c.lng],8.1,{duration:.6});artistList.querySelectorAll(".artist-card").forEach((el,i)=>{el.onclick=e=>{if(!e.target.closest("a"))openArtist(list[i],false)};el.style.cursor="pointer"})}
data.cities.forEach(c=>{const list=byCity.get(c.name)||[];L.marker([c.lat,c.lng],{icon:L.divIcon({className:"",iconSize:[1,1],iconAnchor:[0,0],html:`<div class="city-marker"><div class="city-core"></div><div class="city-label">${esc(c.name)} · ${list.length}</div></div>`}),zIndexOffset:1000}).addTo(map).on("click",()=>openCity(c,list))});
data.cities.forEach(c=>{const list=byCity.get(c.name)||[],baseLat=.048+Math.min(list.length,12)*.0025,baseLng=baseLat*1.45;list.forEach((a,i)=>{const angle=-Math.PI/2+i*2.399963229728653,ring=1+Math.floor(i/8)*.24,lat=c.lat+Math.cos(angle)*baseLat*ring,lng=c.lng+Math.sin(angle)*baseLng*ring;L.polyline([[c.lat,c.lng],[lat,lng]],{color:"#d8ff58",weight:1,opacity:.28,interactive:false,className:"node-line"}).addTo(map);L.marker([lat,lng],{icon:L.divIcon({className:"",iconSize:[1,1],iconAnchor:[0,0],html:`<div class="artist-node"><div class="artist-node-dot"></div><div class="artist-node-label">${esc(a.artist)}</div></div>`}),zIndexOffset:300}).addTo(map).on("click",()=>openArtist(a))})});
let labels=true;$("toggleLabels").onclick=()=>{labels=!labels;$("toggleLabels").classList.toggle("active",labels);document.querySelectorAll(".artist-node-label").forEach(x=>x.classList.toggle("hidden",!labels))};
const unmapped=data.artists.filter(a=>!(a.locations||[]).length);$("unmappedCount").textContent=unmapped.length;$("unmappedBtn").onclick=()=>{kicker.textContent="OTHER ARTISTS";title.textContent="Unmapped";description.textContent=`${unmapped.length} artists have no recognised map location.`;artistList.innerHTML=unmapped.map(card).join("");openPanel()};
const searchable=[...data.cities.map(c=>({type:"city",name:c.name,value:c})),...data.artists.map(a=>({type:"artist",name:a.artist,value:a}))];$("search").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase(),box=$("searchResults");if(!q){box.classList.remove("open");box.innerHTML="";return}const r=searchable.filter(x=>x.name.toLowerCase().includes(q)).slice(0,12);box.innerHTML=r.map((x,i)=>`<div class="result" data-i="${i}"><strong>${esc(x.name)}</strong><span>${x.type}</span></div>`).join("")||"<div class='result'><strong>No matches</strong></div>";box.classList.add("open");box.querySelectorAll("[data-i]").forEach(el=>el.onclick=()=>{const x=r[Number(el.dataset.i)];if(x.type==="city")openCity(x.value,byCity.get(x.value.name)||[]);else openArtist(x.value);box.classList.remove("open");$("search").value=""})});
});
